services:

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
    - "27017:27017"
    volumes:
    - data:/data/db
    env_file: .env

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
    - "8081:8081"
    env_file: .env

volumes:
  data: