name: Docker

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 20
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      
    - name: Build FatJar with Gradle
      run: ./gradlew buildFatJar

    - name: Build Docker Image with Gradle
      run: ./gradlew jibDockerBuild

