name: Docker

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build-jar:
    runs-on: ubuntu-latest
    
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 20
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      
    - name: Build FatJar with Gradle
      run: ./gradlew buildFatJar

    - name: Upload FatJar Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: parlementaire-monitor-all-${{ github.ref_name }}.jar
        path: build/libs/ParlementaireMonitor-all.jar

  build-image:
    runs-on: ubuntu-latest
    needs: build-jar

    steps:

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.3.0
      with:
        name: parlementaire-monitor-all-${{ github.ref_name }}.jar

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ github.repository }}:${{ github.ref_name }}
